In [1]:
import pandas as pd
import numpy as np
X = np.random.randint(0, 100, size=(10, 10))
X

array([[48, 45, 21, 92, 76,  8, 85, 97, 56, 96],
       [72,  6, 95, 84,  4, 86, 95, 21, 31, 84],
       [31, 89, 18, 91, 91, 63, 89, 85, 96, 55],
       [83, 50, 42,  5, 98, 97, 24,  4,  2, 20],
       [34, 21, 90, 68, 87, 79, 83, 42, 19, 32],
       [82, 75, 46, 40, 99, 99, 57, 53, 95, 55],
       [66,  8, 23,  3,  2, 54,  2, 31, 16,  4],
       [55, 24, 54, 97, 72,  4, 54, 83, 30, 35],
       [65, 36, 99, 37, 82, 53, 65, 11, 33, 87],
       [37, 96, 46, 22, 59, 32,  8, 18,  0, 13]])

In [27]:
from sklearn import preprocessing
std = preprocessing.StandardScaler()
std.fit_transform(X)

array([[-0.2593622 , -0.71820501,  0.69029356,  1.26460776,  0.39514539,
        -0.47198982,  0.60309118,  0.85833285, -0.63246063, -1.14868396],
       [-0.228849  ,  2.10673469, -0.03408857, -1.1793533 ,  1.21836494,
        -1.35484847, -1.15979073,  2.19599444,  0.15401891,  1.30869963],
       [-0.62552059,  0.90972634,  1.37206497,  0.26997244, -1.25129372,
        -0.74363864, -1.3144295 , -0.47932874,  1.36650819,  0.93723467],
       [ 0.74757339, -1.19700834, -1.82373853, -1.20777146, -0.09878635,
         1.29372749,  1.25257399, -0.03344154, -1.38617018, -0.49147672],
       [ 0.65603379,  0.23940167,  0.94595784,  1.1793533 ,  0.06585756,
        -1.66045339, -0.44845242, -0.59080053, -1.38617018, -0.46290249],
       [-1.11373179, -0.430923  , -1.35502068, -0.61099027, -0.59271808,
        -0.0984727 ,  1.19071849,  0.26381659, -0.3375308 , -0.00571485],
       [-0.93065259, -0.95760668, -0.07669928, -0.86675363, -0.34575221,
         0.92021037, -0.72680219,  0.82117559

In [25]:
X

array([[34, 38, 72, 91, 64, 39, 65, 60, 25,  7],
       [35, 97, 55,  5, 74, 13,  8, 96, 49, 93],
       [22, 72, 88, 56, 44, 31,  3, 24, 86, 80],
       [67, 28, 13,  4, 58, 91, 86, 36,  2, 30],
       [64, 58, 78, 88, 60,  4, 31, 21,  2, 31],
       [ 6, 44, 24, 25, 52, 50, 84, 44, 34, 47],
       [12, 33, 54, 16, 55, 80, 22, 59, 97,  5],
       [ 0, 44, 36, 99, 74, 92, 57,  9, 39, 89],
       [98, 41, 61, 61, 74, 68, 12, 14, 70, 86],
       [87, 75, 77, 20, 37, 61, 87,  6, 39,  4]])

In [24]:
X2 = (X - X.mean()) / X.std()
X2

array([[-0.48893591, -0.35293149,  0.80310614,  1.44912716,  0.53109728,
        -0.31893038,  0.56509839,  0.39509286, -0.79494587, -1.40696579],
       [-0.45493481,  1.6531338 ,  0.22508733, -1.474968  ,  0.87110835,
        -1.20295915, -1.37296468,  1.61913269,  0.02108069,  1.51712937],
       [-0.89694919,  0.80310614,  1.34712384,  0.25908843, -0.14892485,
        -0.59093923, -1.54297021, -0.82894698,  1.27912163,  1.07511499],
       [ 0.6331006 , -0.69294255, -1.20295915, -1.50896911,  0.32709064,
         1.44912716,  1.27912163, -0.4209337 , -1.57697132, -0.62494034],
       [ 0.53109728,  0.32709064,  1.00711278,  1.34712384,  0.39509286,
        -1.50896911, -0.59093923, -0.9309503 , -1.57697132, -0.59093923],
       [-1.44096689, -0.14892485, -0.82894698, -0.79494587,  0.12308401,
         0.05508179,  1.21111941, -0.14892485, -0.48893591, -0.04692153],
       [-1.23696026, -0.52293702,  0.19108622, -1.10095583,  0.22508733,
         1.07511499, -0.89694919,  0.36109175

In [14]:
X.std()

29.410807537366264

In [2]:
from sklearn import preprocessing
mms = preprocessing.MinMaxScaler()
mms.fit_transform(X)

array([[0.32692308, 0.43333333, 0.03703704, 0.94680851, 0.7628866 ,
        0.04210526, 0.89247312, 1.        , 0.58333333, 1.        ],
       [0.78846154, 0.        , 0.95061728, 0.86170213, 0.02061856,
        0.86315789, 1.        , 0.1827957 , 0.32291667, 0.86956522],
       [0.        , 0.92222222, 0.        , 0.93617021, 0.91752577,
        0.62105263, 0.93548387, 0.87096774, 1.        , 0.55434783],
       [1.        , 0.48888889, 0.2962963 , 0.0212766 , 0.98969072,
        0.97894737, 0.23655914, 0.        , 0.02083333, 0.17391304],
       [0.05769231, 0.16666667, 0.88888889, 0.69148936, 0.87628866,
        0.78947368, 0.87096774, 0.40860215, 0.19791667, 0.30434783],
       [0.98076923, 0.76666667, 0.34567901, 0.39361702, 1.        ,
        1.        , 0.59139785, 0.52688172, 0.98958333, 0.55434783],
       [0.67307692, 0.02222222, 0.0617284 , 0.        , 0.        ,
        0.52631579, 0.        , 0.29032258, 0.16666667, 0.        ],
       [0.46153846, 0.2       , 0.4444444

In [3]:
(X - X.min()) / (X.max() - X.min())

array([[0.48484848, 0.45454545, 0.21212121, 0.92929293, 0.76767677,
        0.08080808, 0.85858586, 0.97979798, 0.56565657, 0.96969697],
       [0.72727273, 0.06060606, 0.95959596, 0.84848485, 0.04040404,
        0.86868687, 0.95959596, 0.21212121, 0.31313131, 0.84848485],
       [0.31313131, 0.8989899 , 0.18181818, 0.91919192, 0.91919192,
        0.63636364, 0.8989899 , 0.85858586, 0.96969697, 0.55555556],
       [0.83838384, 0.50505051, 0.42424242, 0.05050505, 0.98989899,
        0.97979798, 0.24242424, 0.04040404, 0.02020202, 0.2020202 ],
       [0.34343434, 0.21212121, 0.90909091, 0.68686869, 0.87878788,
        0.7979798 , 0.83838384, 0.42424242, 0.19191919, 0.32323232],
       [0.82828283, 0.75757576, 0.46464646, 0.4040404 , 1.        ,
        1.        , 0.57575758, 0.53535354, 0.95959596, 0.55555556],
       [0.66666667, 0.08080808, 0.23232323, 0.03030303, 0.02020202,
        0.54545455, 0.02020202, 0.31313131, 0.16161616, 0.04040404],
       [0.55555556, 0.24242424, 0.5454545

In [5]:
X_cat = pd.DataFrame({
    "name": ["G", "P"],
    "inst": ["B", "D"],
})
X_cat

name inst
0    G    B
1    P    D

In [6]:
pd.get_dummies(X_cat)

name_G  name_P  inst_B  inst_D
0       1       0       1       0
1       0       1       0       1

In [7]:
pd.get_dummies(X_cat, drop_first=True)

name_P  inst_D
0       0       0
1       1       1

In [18]:
from sklearn import preprocessing
lab = preprocessing.LabelEncoder()
lab.fit_transform(X_cat.name)

array([0, 1])

In [17]:
lab.inverse_transform([0, 1])

array(['G', 'P'], dtype=object)

In [21]:
X_cat.name.astype("category").cat.codes

0    0
1    1
dtype: int8

In [23]:
maping = X_cat.name.value_counts()
X_cat.name.map(maping)

0    1
1    1
Name: name, dtype: int64

In [24]:
from categorical_encoder import CategoricalEncoder

ModuleNotFoundError: No module named 'categorical_encoder'

In [1]:
from sklearn.metrics import accuracy_score
X = [1, 2]
Y = [1, 2]
accuracy_score(X, Y)

1.0

In [26]:
from sklearn.metrics import recall_score
recall_score(X, Y)

1.0

In [27]:
from sklearn.metrics import precision_score
precision_score(X, Y)

1.0

In [28]:
from sklearn.metrics import f1_score
f1_score(X, Y)

1.0

In [29]:
from sklearn.metrics import roc_auc_score
roc_auc_score(X, Y)

1.0

In [30]:
from sklearn.metrics import average_precision_score
average_precision_score(X, Y)

0.5

In [2]:
from sklearn.metrics import r2_score
Y_test = [1, 2]
Y_predict = [1, 2]
r2_score(Y_test, Y_predict)

1.0

In [3]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(Y_test, Y_predict)

0.0

In [4]:
from sklearn.metrics import mean_squared_error
mean_squared_error(Y_test, Y_predict)

0.0

In [5]:
from sklearn.metrics import mean_squared_log_error
mean_squared_log_error(Y_test, Y_predict)

0.0