In [10]:
from transformers import TFAutoModelForSequenceClassification, AutoTokenizer
import tensorflow as tf

In [3]:
my_model = TFAutoModelForSequenceClassification.from_pretrained("./output")
my_tokenizer = AutoTokenizer.from_pretrained("./output")

Some layers from the model checkpoint at ./output were not used when initializing TFBertForSequenceClassification: ['dropout_37']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at ./output.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [25]:
result = my_model(my_tokenizer("新闻摄影也要NFT 美联社连摊子都支好了", return_tensors="tf"))
print(result)
print(tf.nn.softmax(result.logits, axis=1))

tf.argmax(tf.nn.softmax(result.logits, axis=1), axis=1)

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(1, 25), dtype=float32, numpy=
array([[-0.72052294,  1.1747351 , -1.0982342 , -0.37767336, -1.0921919 ,
        -1.2597075 , -0.68110037, -1.5146378 , -0.99611294, -0.46207786,
        -2.2787147 , -0.73325366, -1.7068146 , -0.84196067,  1.2893516 ,
        -2.7350929 , -3.3782663 , -1.4319956 ,  0.88496804, -1.9387099 ,
         2.5381165 ,  6.9129324 ,  0.9050839 ,  0.58762884,  1.5133077 ]],
      dtype=float32)>, hidden_states=None, attentions=None)
tf.Tensor(
[[4.6712288e-04 3.1083594e-03 3.2017927e-04 6.5815606e-04 3.2211983e-04
  2.7243712e-04 4.8590585e-04 2.1113068e-04 3.5460424e-04 6.0488423e-04
  9.8337070e-05 4.6121384e-04 1.7421680e-04 4.1370548e-04 3.4858484e-03
  6.2303785e-05 3.2748234e-05 2.2932033e-04 2.3264135e-03 1.3815898e-04
  1.2151790e-02 9.6515858e-01 2.3736851e-03 1.7280417e-03 4.3608528e-03]], shape=(1, 25), dtype=float32)


<tf.Tensor: shape=(1,), dtype=int64, numpy=array([21], dtype=int64)>

In [19]:
my_model.config.id2label

{0: '体育_CBA',
 1: '体育_NBA',
 2: '体育_中国足球',
 3: '体育_国际足球',
 4: '娱乐_明星',
 5: '娱乐_电影',
 6: '娱乐_电视',
 7: '娱乐_音乐',
 8: '政务_反腐',
 9: '政务_发展治理',
 10: '政务_地方',
 11: '政务_政策',
 12: '政务_文旅',
 13: '时尚_情感',
 14: '时尚_时装',
 15: '时尚_美容',
 16: '汽车_导购',
 17: '汽车_新车',
 18: '汽车_行业',
 19: '汽车_试驾',
 20: '科技_5G',
 21: '科技_区块链',
 22: '科技_手机',
 23: '科技_数码',
 24: '科技_车科技'}