In [1]:
import tensorflow as tf
import torch
import numpy as np

In [168]:
# TODO: 我的场景如下
a = tf.Variable([[1, 2, 3], [4, 5, 6]])
indices = tf.constant([1, 0])
# 然后要对 a 的 axis=0 上的每个进行操作, 将 indices 对应的值都变成某个值
print(tf.gather(a, indices))
print(tf.gather(a, indices, axis=1))
print(tf.gather(a, indices, batch_dims=1))

tf.Tensor(
[[4 5 6]
 [1 2 3]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[2 1]
 [5 4]], shape=(2, 2), dtype=int32)
tf.Tensor([2 4], shape=(2,), dtype=int32)


In [161]:
a = tf.Variable([[1, 2, 3], [4, 5, 6]])
a = tf.transpose(a, perm=[1, 0])
indices = tf.constant([1, 0])
print(a)
print(indices.shape.rank)
print(tf.constant([[1], [0]]).shape)
print(tf.ones([2, 2], dtype=tf.int32))
result = tf.tensor_scatter_nd_update(a, tf.reshape(indices, (-1, 1)), tf.zeros([2, 2], dtype=tf.int32))
print(result)
tf.transpose(result, perm=[1, 0])

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
1
(2, 1)
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0 0]
 [0 0]
 [3 6]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 3],
       [0, 0, 6]])>

In [167]:
# a 是 (2, 3)
a = tf.Variable([[1, 2, 3, 1], [4, 5, 6, 2]])
# 调换 axis 的顺序, 变成 (3, 2)
a = tf.transpose(a, perm=[1, 0])
# 定义需要修改的列的索引. 其实现在是行, 因为 a 已经改变了行列的顺序
indices = tf.constant([1, 0])
# 首先, indices 必须先变成 (2, 1) 的形状, 因为要求 rank 必须 >= 2
# 然后定义 update 的形状, 第一个维度是 indices.shape[0], 第二个维度是 a.shape[1:]
updates = tf.zeros([indices.shape[0]] + a.shape[1:], dtype=tf.int32)
result = tf.tensor_scatter_nd_update(a, tf.reshape(indices, (-1, 1)), updates)
tf.transpose(result, perm=[1, 0])

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 0, 3, 1],
       [0, 0, 6, 2]])>

In [137]:
tf.ones(a.shape)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [3]:
a = [[1, 2, 3, 4, 5]]
tf_a = tf.constant(a)
tf_a

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 2, 3, 4, 5]])>

In [42]:
tf.gather(tf_a, axis=1, indices=[3, 1, 1, 2]).numpy()

array([[4, 2, 2, 3]])

In [46]:
tf.gather(tf_a, axis=1, indices=[0, 1])

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]])>

In [77]:
tf.tensor_scatter_nd_update(tf_a, [[0, 0], [0, 1]], [10, 10])

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[10, 10,  3,  4,  5]])>

In [17]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
tf.gather(params, indices=[2,1], axis=1).numpy()

array([[ 2.,  1.],
       [12., 11.],
       [22., 21.],
       [32., 31.]], dtype=float32)

In [35]:
tf.expand_dims(params[3], 0).numpy()

array([[30., 31., 32.]], dtype=float32)

In [23]:
params[:, 2].numpy()

array([ 2., 12., 22., 32.], dtype=float32)

In [39]:
np.concatenate([tf.expand_dims(params[:, 2], 1).numpy() , tf.expand_dims( params[:, 1], 1).numpy()], axis=1)

array([[ 2.,  1.],
       [12., 11.],
       [22., 21.],
       [32., 31.]], dtype=float32)

In [101]:
np.stack([params[:, 2], params[:, 1]], axis=1)

array([[1, 0],
       [0, 0],
       [0, 5]])

In [78]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
print(params.shape)

(4, 3)


In [79]:
tf.gather(params, indices=[3,1], axis=0).shape

TensorShape([2, 3])

In [83]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
print(params.shape)
tf.gather(params, [[2, 0], [2, 5]]).numpy().shape

(6,)


(2, 2)

In [95]:
params = tf.constant([
    [0, 0, 1, 0, 2],
    [3, 0, 0, 0, 4],
    [0, 5, 0, 6, 0]])
indices = tf.constant([
    [2, 4],
    [0, 4],
    [1, 3]])
tf.gather(params, indices, axis=1, batch_dims=0).numpy()

array([[[1, 2],
        [0, 2],
        [0, 0]],

       [[0, 4],
        [3, 4],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [5, 6]]])

In [88]:
tf.gather(params, indices, axis=1, batch_dims=1).numpy()

array([[1, 2],
       [3, 4],
       [5, 6]])

In [93]:
def manually_batched_gather(params, indices, axis):
  batch_dims=1
  result = []
  for p,i in zip(params, indices):
    print(p, i)
    r = tf.gather(p, i, axis=axis-batch_dims)
    print(r)
    result.append(r)
  return tf.stack(result)
manually_batched_gather(params, indices, axis=1).numpy()

tf.Tensor([0 0 1 0 2], shape=(5,), dtype=int32) tf.Tensor([2 4], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([3 0 0 0 4], shape=(5,), dtype=int32) tf.Tensor([0 4], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([0 5 0 6 0], shape=(5,), dtype=int32) tf.Tensor([1 3], shape=(2,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [117]:
tf.gather_nd(
    batch_dims = 1,
    indices = [[[1]], [[0]]],
    params = [[['a0', 'b0'], ['c0', 'd0']],
              [['a1', 'b1'], ['c1', 'd1']]]).numpy().shape

(2, 1, 2)